#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = waybar 
# exec-once = swww-daemon & swww img ~/Bilder/wallpaper/gruvbox/anime/wall.jpg
exec-once = hyprpaper
exec-once = agsv1
exec-once = udiskie
exec-once = swayidle -w timeout 300 'hyprlock'
# exec-once = swayidle -w 300 'hyprlock'
# exec-once = nm-applet
