# Preload Wallpaper
preload = ~/Pictures/wallpaper/gruvbox/anime/ign-waifu.png
preload = ~/Pictures/wallpaper/gruvbox/light/face.png

# Set wallpaper
# wallpaper = ,~/Pictures/wallpaper/gruvbox/anime/ign-waifu.png
wallpaper = ,~/Pictures/wallpaper/gruvbox/light/face.png

# Disable splash
splash = false
