#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal

# Wallpaper stuff
# exec-once = swww-daemon & swww img -t none --transition-duration 0 ~/Pictures/wallpaper/gruvbox/light/face.png
# exec-once = swww img -t none --transition-duration 0 ~/Pictures/wallpaper/gruvbox/light/face.png
# exec-once = hyprpaper

# Autostart for bars hyprpanel also manages the wallpaper
# exec-once = hyprpanel
# Alternatively, you can use waybar with swww-daemon and dunst
exec-once = waybar 
exec-once = swww-daemon
exec-once = dunst

# other stuff
exec-once = udiskie
exec-once = swayidle -w timeout 300 'hyprlock'
exec-once = battery-notify
# exec-once = swayidle -w 300 'hyprlock'
# exec-once = nm-applet
