# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        scroll_factor = 0.4
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = true
}

device {
    name = razer-razer-viper-ultimate-dongle-1
    sensitivity = -0.6
}

device {
    name = finalmouse-ultralightx-dongle-mouse
    sensitivity = -0.8
}
