# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = razer-razer-viper-ultimate-dongle-1
    sensitivity = -0.6
}
device {
    name = finalmouse-ultralightx-dongle-mouse
    sensitivity = -0.6
}
