##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Remove the right-click menu blurring in Cromium browsers
windowrulev2 = noblur, class:^()$, title:^()$

# Ignore maximize requests from apps. 
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Make file picker windows floating
windowrulev2 = float, center, title:^(Open File|Open|Save|Save As|Export|Import|Choose File|Rename), class:^(.*)$

# Disable boarders for swaync
windowrulev2 = noborder, class:(swaync)

# Blur Waybar
layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = ignorealpha 0.5, waybar

# Blur swaync
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window

layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window

layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window

# Blur wlogout
layerrule = blur, logout_dialog

# Blur rofi
layerrule = dimaround, rofi
layerrule = blur, rofi
layerrule = animation slide top, rofi

windowrulev2 = float,class:^(jetbrains-clion)$,title:^(Welcome to CLion)$
windowrulev2 = float,class:^(jetbrains-idea)$,title:^(Welcome to IntelliJ IDEA)$
windowrulev2 = float,class:^(jetbrains-rustrover)$,title:^(Welcome to RustRover)$

windowrulev2 = float,class:^(KeePass2)$
windowrulev2 = center, class:^(KeePass2)$
windowrulev2 = size 1000 600, class:^(KeePass2)$, title:^(KeePass)$
windowrulev2 = size 1000 600, class:^(KeePass2)$, title:^(Database.kdbx - KeePass)$
windowrulev2 = size 550 300, class:^(KeePass2)$, title:^(Open Database - Database.kdbx)$

windowrulev2 = size 900 800, class:^(Vivaldi-stable)$, title:^(Vivaldi Settings: Start Page - Vivaldi)$
windowrulev2 = center, class:^(Vivaldi-stable)$, title:^(Vivaldi Settings: Start Page - Vivaldi)$
windowrulev2 = size 900 800, class:^(Vivaldi-stable)$, title:^(Vivaldi Settings: General - Vivaldi)$
windowrulev2 = center, class:^(Vivaldi-stable)$, title:^(Vivaldi Settings: General - Vivaldi)$
windowrulev2 = size 1000 800, class:^(Nsxiv)$, title:^(nsxiv)$

windowrulev2 = workspace 9, class:^(.*Docker Desktop.*)$
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# windowrule for inactive opacity
windowrulev2 = opacity 1.2, class:^(jetbrains-studio)$
windowrulev2 = opacity 1.2, class:^(jetbrains-idea)$
windowrulev2 = opacity 1.2, class:^(jetbrains-studio)$
windowrulev2 = opacity 1.2, class:^(jetbrains-rustrover)$

# Android Emulator
windowrulev2 = float,class:^(Emulator)$

# AI assistant
windowrulev2 = float,class:^(askai)$
windowrulev2 = size 90% 80%,class:^(askai)$
windowrulev2 = center,class:^(askai)$

# yazi drop window
windowrulev2 = float,class:^(dropterm)$
windowrulev2 = workspace special:drop,class:^(dropterm)$
windowrulev2 = size 90% 80%,class:^(dropterm)$
windowrulev2 = center,class:^(dropterm)$

# installer window
windowrulev2 = float,class:^(installer)$
windowrulev2 = size 90% 80%,class:^(installer)$
windowrulev2 = center,class:^(installer)$

# waybar sound settings window
windowrulev2 = float,class:^(floating_waybar)$
# windowrulev2 = workspace special:drop,class:^(floating_waybar)$
windowrulev2 = size 90% 80%,class:^(floating_waybar)$
windowrulev2 = center,class:^(floating_waybar)$
