##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules


# Ignore maximize requests from apps. 
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Example windowrule v1
# windowrule = float, ^(kitty)$
windowrulev2 = float,class:^(jetbrains-clion)$,title:^(Welcome to CLion)$
windowrulev2 = float,class:^(jetbrains-idea)$,title:^(Welcome to IntelliJ IDEA)$
windowrulev2 = float,class:^(jetbrains-rustrover)$,title:^(Welcome to RustRover)$

windowrulev2 = float,class:^(KeePass2)$
windowrulev2 = center, class:^(KeePass2)$
windowrulev2 = size 1000 600, class:^(KeePass2)$, title:^(KeePass)$
windowrulev2 = size 1000 600, class:^(KeePass2)$, title:^(Database.kdbx - KeePass)$
windowrulev2 = size 550 300, class:^(KeePass2)$, title:^(Open Database - Database.kdbx)$

windowrulev2 = size 900 800, class:^(Vivaldi-stable)$, title:^(Vivaldi Settings: Start Page - Vivaldi)$
windowrulev2 = center, class:^(Vivaldi-stable)$, title:^(Vivaldi Settings: Start Page - Vivaldi)$
windowrulev2 = size 900 800, class:^(Vivaldi-stable)$, title:^(Vivaldi Settings: General - Vivaldi)$
windowrulev2 = center, class:^(Vivaldi-stable)$, title:^(Vivaldi Settings: General - Vivaldi)$
windowrulev2 = size 1000 800, class:^(Nsxiv)$, title:^(nsxiv)$

windowrulev2 = workspace 9, class:^(.*Docker Desktop.*)$
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# windowrule for inactive opacity
windowrulev2 = opacity 1.2, class:^(jetbrains-studio)$
windowrulev2 = opacity 1.2, class:^(jetbrains-idea)$
windowrulev2 = opacity 1.2, class:^(jetbrains-studio)$
windowrulev2 = opacity 1.2, class:^(jetbrains-rustrover)$

# Android Emulator
windowrulev2 = center,class:^(dropterm)$indowrulev2 = float,class:^(Emulator)$

# yazi drop window
windowrulev2 = float,class:^(dropterm)$
windowrulev2 = workspace special:drop,class:^(dropterm)$
windowrulev2 = size 90% 80%,class:^(dropterm)$
windowrulev2 = center,class:^(dropterm)$
